github:
  prebuilds:
    master: true
    branches: true

ports:
  - name: Instructions webpage
    port: 8000
    visibility: private
    # do not notify once the port is detected
    onOpen: ignore

tasks:
  - name: Open instructions in browser
    init: |
      cd java
      pip install grip
      grip gitpod.md 8000 &
      while true; do
        curl -I http://localhost:8000 < /dev/null
        if [ $? -eq 0 ]; then
          break
        fi
        sleep 1
      done
      rm -rf README.md media
    command: |
      gp sync-done file-setup
      gp preview http://localhost:8000
  - name: Terminal
    init: |
      curl -L --http1.1 https://cnfl.io/cli | sudo sh -s -- -b /usr/local/bin
    command: |
      gp sync-done code-copy
      rm -rf !(java)
      rm -rf .github/
      rm -f .*
      rm -f java/src/main/java/io/confluent/developer/*OAuth.java
      rm -f java/src/main/java/io/confluent/developer/*Existing.java
      rm -f java/src/main/java/io/confluent/developer/*Local.java
      mv java/src/main/java/io/confluent/developer/ConsumerExampleCloudBasic.java java/src/main/java/io/confluent/developer/ConsumerExample.java
      mv java/src/main/java/io/confluent/developer/ProducerExampleCloudBasic.java java/src/main/java/io/confluent/developer/ProducerExample.java
      cd java
      gp open src/main/java/io/confluent/developer/ConsumerExample.java
      gp open src/main/java/io/confluent/developer/ProducerExample.java
      gp sync-done file-setup
      clear

vscode:
  extensions:
    - github.github-vscode-theme
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-gradle
