basePath: /getting-started
languages:
  - path: java
    name: Java
  - path: python
    name: Python
  - path: go
    name: Go
  - path: dotnet
    name: .NET
  - path: nodejs
    name: Node.js
  - path: c
    name: C
  - path: rest
    name: REST

