basePath: /get-started
languages:
  - path: java
    name: Java
  - path: python
    name: Python
  - path: go
    name: Go
  - path: dotnet
    name: .NET
  - path: nodejs
    name: Node.js
  - path: c
    name: C/C++
  - path: rest
    name: REST
  - path: springboot
    name: Spring Boot
  - path: more
    name: ...and more
    url: /kafka-languages-and-tools
