spring:
  kafka:
    bootstrap-servers: {{ kafka.broker.server }}
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        jaas:
          config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
            clientId='< OAUTH2 CLIENT ID >'
            clientSecret='< OAUTH2 CLIENT SECRET >'
            scope='< OAUTH2 SCOPE >'
            extension_logicalCluster='< LOGICAL CLUSTER ID >'
            extension_identityPoolId='< IDENTITY POOL ID >';
        mechanism: OAUTHBEARER
        login:
          callback:
            handler:
              class: org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler
        oauthbearer:
          token:
            endpoint:
              url: < OAUTH2 TOKEN ENDPOINT URL >
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
