buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id "java"
    id "idea"
    id "eclipse"
    id("com.github.johnrengelman.shadow") version "7.0.0"
}

sourceCompatibility = "1.11"
targetCompatibility = "1.11"
version = "0.0.1"

repositories {
    mavenCentral()
    gradlePluginPortal()

    maven {
        url "https://packages.confluent.io/maven"
    }
}

dependencies {
    implementation group: 'org.slf4j', name: 'slf4j-nop', version: '2.0.17'
    implementation group: 'org.apache.kafka', name: 'kafka-clients', version: '4.2.0'

    // needed if OAuth is used; otherwise this can be left out.
    // See: https://docs.confluent.io/platform/current/security/authentication/sasl/oauthbearer/overview.html
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.21.0'
}

jar {
    manifest {
        attributes(
                "Class-Path": configurations.compileClasspath.collect { it.getName() }.join(" "),
                "Main-Class": "io.confluent.developer.ProducerExample"
        )
    }
}

shadowJar {
    archiveBaseName = "kafka-java-getting-started"
    archiveClassifier = ''
}
