plugins {
    id "java"
    id "idea"
    id "eclipse"
    id "com.gradleup.shadow" version "9.1.0"
}

version = "0.0.1"

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()

    maven {
        url = "https://packages.confluent.io/maven"
    }
}

dependencies {
    implementation "org.slf4j:slf4j-nop:2.0.3"
    implementation "org.apache.kafka:kafka-clients:4.3.1"

    // needed if OAuth is used; otherwise this can be left out.
    // See: https://docs.confluent.io/platform/current/kafka/authentication_sasl/authentication_sasl_oauth.html
    implementation "com.fasterxml.jackson.core:jackson-databind:2.15.2"
}

jar {
    manifest {
        attributes(
                "Class-Path": configurations.compileClasspath.collect { it.getName() }.join(" "),
                "Main-Class": "io.confluent.developer.ProducerExample"
        )
    }
}

shadowJar {
    archiveBaseName = "kafka-java-getting-started"
    archiveClassifier = ''
}
